### ISSUE TITLE
Endogeneity-robust feature

### ISSUE THREAD

**Issue by longhaivo** [yukai-yang/PSTR#4]
Hi Yukai,
Just out of curiosity, does this package allow for endogenous regressors? Let's say for example in the investment-cash flow volatility regression, what if investment level somehow reversely affecting cash flow vol? (e.g., low investment could lead to lower stock prices, causing financial constrains etc. and thus making cash flow more volatile in the future). 
A possible solution is adopting an instrumental variable approach for the PSTR model, as outlined in section 6 in the paper by Fouquau et al. here: http://www.univ-orleans.fr/deg/masters/ESA/CH/FH.pdf (the published version is at https://www.sciencedirect.com/science/article/pii/S0264999307000831). 

Regards,
Long

**Comment by yukai-yang** [comment]
This is a very interesting topic. Thank you for sharing the papers!

Unfortunately in the current version of the package, the endogeneity problem is not handled. Actually the endogeneity is not the focus of the corresponding paper, and we just implement the method introduced there. But I agree with you that this is of great importance in practice as the regressors are most probably endogenous.
