### ISSUE TITLE
PSTR Application for Unbalanced Panel Data

### ISSUE THREAD

**Issue by aliawaischeema** [yukai-yang/PSTR#6]
Hi, i am applying the Panel Smooth transition model on banking data but it is unbalanced data and PSTR package in R uses the balanced data. Can i apply the PSTR package on unbalanced data with some missing values in observations for instance, some value are missing in investment or tobin,s Q ratio.
It would be great contribution if we this package can be applied on unbalanced panel data having missing observations in dependent, independent or transition variable.
Alternatively, the code for Panel Smooth transition code  is available in RATS Programming language developed by Gonzalez, A., Teräsvirta, T., Van Dijk, D., & Yang, Y. (2017). Panel smooth transition regression models.

**Comment by yukai-yang** [comment]
Unfortunately no... The PSTR package follows the PSTR modelling procedure in the paper, and it does not consider the unbalanced case.

I am not sure if the RATS package allows for it... In my opinion, the missing values should be carefully treated, which can be very difficult...

**Comment by RoyaTaherifar** [comment]
Hello, I am trying to run the PSTR package in R. however I am getting the following Erorr. I would really appreciate if let me now how I can solve this problem

pstr = LinTest(use=pstr) 
Error in if (class(invS1) == "try-error") { : 
  the condition has length > 1
