### ISSUE TITLE
What issue of R was this created in?

### ISSUE THREAD

**Issue by youngceltic** [yukai-yang/PSTR#7]
I've tried R versions down to 3.4.0 and the installation does not work.

**Comment by youngceltic** [comment]
The description says R versions 3.0.0 or higher, but none of those versions work with PSTR?

> 
> 
> I've tried R versions down to 3.4.0 and the installation does not work.

**Comment by yukai-yang** [comment]
I am going to solve this asap!!! I just noticed this... Sorry
